# this file is customized from https://gist.github.com/chitoku-k/67068aa62aa3f077f5307ca9a822ce74#file-travis-yml
language: node_js
sudo: true
dist: trusty

matrix:
  include:
    - os: linux
      node_js: '7.10.0'
      sudo: required
      env: DISPLAY=':99.0'
      dist: trusty
      addons:
        apt:
          sources:
            - google-chrome
          packages:
            - google-chrome-stable
    - os: osx
      node_js: '7.10.0'
      sudo: required
      env: HOMEBREW_CASK_OPTS='--appdir=/Applications'

before_install:
  - |
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew update > /dev/null
      brew cask install google-chrome
    fi

install:
  - npm install

before_script:
  - |
    if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      sh -e /etc/init.d/xvfb start
    fi

script:
    # karma unit test
  - ng test --watch false
    # e2e test
  - ng e2e --watch false
    # check format
  - ng lint
    # build
  - ng build